### ISSUE TITLE
Bundler cannot find correct path

### ISSUE THREAD

**Issue by riseshia** [riseshia/Bonghwa#341]
bundler: failed to load command: rubocop
Gem::Exception: can't find executable rubocop
  /Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.4/lib/bundler/rubygems_integration.rb:407:in `block in replace_bin_path'
  /Users/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.4/lib/bundler/rubygems_integration.rb:424:in `block in replace_bin_path'
  /Users/user/.rbenv/versions/2.4.0/bin/cap:22:in `<top (required)>'

**Comment by riseshia** [comment]
re-clone project XD
close it
