### ISSUE TITLE
Broken test ;_;

### ISSUE THREAD

**Issue by riseshia** [riseshia/Bonghwa#478]
```
/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/test_unit/minitest_plugin.rb:9:in `aggregated_results': wrong number of arguments (given 1, expected 0) (ArgumentError)
  from /.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:597:in `report'
  from /.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:687:in `each'
  from /.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:687:in `report'
  from /.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:141:in `run'
  from /.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/test_unit/minitest_plugin.rb:72:in `run'
  from /.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:63:in `block in autorun'
```

**Comment by riseshia** [comment]
related https://github.com/rails/rails/pull/29022, https://github.com/seattlerb/minitest/issues/689

**Comment by riseshia** [comment]
딱히 테스트가 안되는게 아니고, 레포팅에 문제가 있는거라서 일단 수정 없이 두다가 없어지면 그때 처리하는 것으로...
travis 실패 메일이 좀 귀찮긴 하지만 ㅇ<-<
